name: Deploy to Dev Sandbox
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install sfdx CLI
        run: npm install -g sfdx-cli

      - name: Authenticate to Dev Sandbox
        run: sfdx force:auth:login -i https://test.salesforce.com -u "${{ secrets.SF_USERNAME }}" -p "${{ secrets.SF_PASSWORD }}" --setdefaultusername

      - name: Deploy Metadata
        run: sfdx force:source:deploy -p force-app