name: Deploy to Dev Sandbox
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate to Dev Sandbox
        run: sf org login userpass --instance-url https://test.salesforce.com --username ${{ secrets.SF_USERNAME }} --password ${{ secrets.SF_PASSWORD }} --set-default
      
      - name: Deploy Metadata
        run: sf project deploy start